baseURL = "https://ragib.dev/"
locale = "en-us"
title = "ragib.dev"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

pagination.pagerSize = 10

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  description = "Personal dev blog by Ragib Badaruddin"
  author = "Ragib Badaruddin"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  disableSpecial1stPost = false
  comments = false

  [params.homeInfoParams]
    Title = "Hi, I'm Ragib \U0001F44B"
    Content = "Notes on infra, Kubernetes, and whatever else I'm building."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ragibkl"

  [params.assets]
    disableHLJS = true
    favicon = "/favicon.ico"

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = false
  style = "monokai"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30
